//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18010
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace Umebayashi.Enterprise.SharePoint.Services.Permissions {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", ConfigurationName="SharePoint.Services.Permissions.PermissionsSoap")]
    public interface PermissionsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/directory/GetPermissionCollection", ReplyAction="*")]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionResponse> GetPermissionCollectionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/directory/AddPermission", ReplyAction="*")]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionResponse> AddPermissionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/directory/AddPermissionCollection", ReplyAction="*")]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionResponse> AddPermissionCollectionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/directory/UpdatePermission", ReplyAction="*")]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionResponse> UpdatePermissionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/directory/RemovePermission", ReplyAction="*")]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionResponse> RemovePermissionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/directory/RemovePermissionCollection" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionResponse> RemovePermissionCollectionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissionCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissionCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionRequestBody Body;
        
        public GetPermissionCollectionRequest() {
        }
        
        public GetPermissionCollectionRequest(Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/")]
    public partial class GetPermissionCollectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string objectType;
        
        public GetPermissionCollectionRequestBody() {
        }
        
        public GetPermissionCollectionRequestBody(string objectName, string objectType) {
            this.objectName = objectName;
            this.objectType = objectType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissionCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissionCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionResponseBody Body;
        
        public GetPermissionCollectionResponse() {
        }
        
        public GetPermissionCollectionResponse(Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/")]
    public partial class GetPermissionCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetPermissionCollectionResult;
        
        public GetPermissionCollectionResponseBody() {
        }
        
        public GetPermissionCollectionResponseBody(System.Xml.Linq.XElement GetPermissionCollectionResult) {
            this.GetPermissionCollectionResult = GetPermissionCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPermissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPermission", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionRequestBody Body;
        
        public AddPermissionRequest() {
        }
        
        public AddPermissionRequest(Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/")]
    public partial class AddPermissionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string objectType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string permissionIdentifier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string permissionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int permissionMask;
        
        public AddPermissionRequestBody() {
        }
        
        public AddPermissionRequestBody(string objectName, string objectType, string permissionIdentifier, string permissionType, int permissionMask) {
            this.objectName = objectName;
            this.objectType = objectType;
            this.permissionIdentifier = permissionIdentifier;
            this.permissionType = permissionType;
            this.permissionMask = permissionMask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPermissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPermissionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionResponseBody Body;
        
        public AddPermissionResponse() {
        }
        
        public AddPermissionResponse(Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddPermissionResponseBody {
        
        public AddPermissionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPermissionCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPermissionCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionRequestBody Body;
        
        public AddPermissionCollectionRequest() {
        }
        
        public AddPermissionCollectionRequest(Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/")]
    public partial class AddPermissionCollectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string objectType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement permissionsInfoXml;
        
        public AddPermissionCollectionRequestBody() {
        }
        
        public AddPermissionCollectionRequestBody(string objectName, string objectType, System.Xml.Linq.XElement permissionsInfoXml) {
            this.objectName = objectName;
            this.objectType = objectType;
            this.permissionsInfoXml = permissionsInfoXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPermissionCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPermissionCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionResponseBody Body;
        
        public AddPermissionCollectionResponse() {
        }
        
        public AddPermissionCollectionResponse(Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddPermissionCollectionResponseBody {
        
        public AddPermissionCollectionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePermissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePermission", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionRequestBody Body;
        
        public UpdatePermissionRequest() {
        }
        
        public UpdatePermissionRequest(Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/")]
    public partial class UpdatePermissionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string objectType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string permissionIdentifier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string permissionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int permissionMask;
        
        public UpdatePermissionRequestBody() {
        }
        
        public UpdatePermissionRequestBody(string objectName, string objectType, string permissionIdentifier, string permissionType, int permissionMask) {
            this.objectName = objectName;
            this.objectType = objectType;
            this.permissionIdentifier = permissionIdentifier;
            this.permissionType = permissionType;
            this.permissionMask = permissionMask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePermissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePermissionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionResponseBody Body;
        
        public UpdatePermissionResponse() {
        }
        
        public UpdatePermissionResponse(Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdatePermissionResponseBody {
        
        public UpdatePermissionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePermissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemovePermission", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionRequestBody Body;
        
        public RemovePermissionRequest() {
        }
        
        public RemovePermissionRequest(Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/")]
    public partial class RemovePermissionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string objectType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string permissionIdentifier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string permissionType;
        
        public RemovePermissionRequestBody() {
        }
        
        public RemovePermissionRequestBody(string objectName, string objectType, string permissionIdentifier, string permissionType) {
            this.objectName = objectName;
            this.objectType = objectType;
            this.permissionIdentifier = permissionIdentifier;
            this.permissionType = permissionType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePermissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemovePermissionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionResponseBody Body;
        
        public RemovePermissionResponse() {
        }
        
        public RemovePermissionResponse(Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RemovePermissionResponseBody {
        
        public RemovePermissionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePermissionCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemovePermissionCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionRequestBody Body;
        
        public RemovePermissionCollectionRequest() {
        }
        
        public RemovePermissionCollectionRequest(Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/")]
    public partial class RemovePermissionCollectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string objectType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement memberIdsXml;
        
        public RemovePermissionCollectionRequestBody() {
        }
        
        public RemovePermissionCollectionRequestBody(string objectName, string objectType, System.Xml.Linq.XElement memberIdsXml) {
            this.objectName = objectName;
            this.objectType = objectType;
            this.memberIdsXml = memberIdsXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePermissionCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemovePermissionCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/directory/", Order=0)]
        public Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionResponseBody Body;
        
        public RemovePermissionCollectionResponse() {
        }
        
        public RemovePermissionCollectionResponse(Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RemovePermissionCollectionResponseBody {
        
        public RemovePermissionCollectionResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PermissionsSoapChannel : Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PermissionsSoapClient : System.ServiceModel.ClientBase<Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap>, Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PermissionsSoapClient() : 
                base(PermissionsSoapClient.GetDefaultBinding(), PermissionsSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.PermissionsSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PermissionsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PermissionsSoapClient.GetBindingForEndpoint(endpointConfiguration), PermissionsSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PermissionsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PermissionsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PermissionsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PermissionsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PermissionsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionResponse> Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap.GetPermissionCollectionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionRequest request) {
            return base.Channel.GetPermissionCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionResponse> GetPermissionCollectionAsync(string objectName, string objectType) {
            Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionRequest inValue = new Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionRequest();
            inValue.Body = new Umebayashi.Enterprise.SharePoint.Services.Permissions.GetPermissionCollectionRequestBody();
            inValue.Body.objectName = objectName;
            inValue.Body.objectType = objectType;
            return ((Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap)(this)).GetPermissionCollectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionResponse> Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap.AddPermissionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionRequest request) {
            return base.Channel.AddPermissionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionResponse> AddPermissionAsync(string objectName, string objectType, string permissionIdentifier, string permissionType, int permissionMask) {
            Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionRequest inValue = new Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionRequest();
            inValue.Body = new Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionRequestBody();
            inValue.Body.objectName = objectName;
            inValue.Body.objectType = objectType;
            inValue.Body.permissionIdentifier = permissionIdentifier;
            inValue.Body.permissionType = permissionType;
            inValue.Body.permissionMask = permissionMask;
            return ((Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap)(this)).AddPermissionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionResponse> Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap.AddPermissionCollectionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionRequest request) {
            return base.Channel.AddPermissionCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionResponse> AddPermissionCollectionAsync(string objectName, string objectType, System.Xml.Linq.XElement permissionsInfoXml) {
            Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionRequest inValue = new Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionRequest();
            inValue.Body = new Umebayashi.Enterprise.SharePoint.Services.Permissions.AddPermissionCollectionRequestBody();
            inValue.Body.objectName = objectName;
            inValue.Body.objectType = objectType;
            inValue.Body.permissionsInfoXml = permissionsInfoXml;
            return ((Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap)(this)).AddPermissionCollectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionResponse> Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap.UpdatePermissionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionRequest request) {
            return base.Channel.UpdatePermissionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionResponse> UpdatePermissionAsync(string objectName, string objectType, string permissionIdentifier, string permissionType, int permissionMask) {
            Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionRequest inValue = new Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionRequest();
            inValue.Body = new Umebayashi.Enterprise.SharePoint.Services.Permissions.UpdatePermissionRequestBody();
            inValue.Body.objectName = objectName;
            inValue.Body.objectType = objectType;
            inValue.Body.permissionIdentifier = permissionIdentifier;
            inValue.Body.permissionType = permissionType;
            inValue.Body.permissionMask = permissionMask;
            return ((Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap)(this)).UpdatePermissionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionResponse> Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap.RemovePermissionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionRequest request) {
            return base.Channel.RemovePermissionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionResponse> RemovePermissionAsync(string objectName, string objectType, string permissionIdentifier, string permissionType) {
            Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionRequest inValue = new Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionRequest();
            inValue.Body = new Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionRequestBody();
            inValue.Body.objectName = objectName;
            inValue.Body.objectType = objectType;
            inValue.Body.permissionIdentifier = permissionIdentifier;
            inValue.Body.permissionType = permissionType;
            return ((Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap)(this)).RemovePermissionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionResponse> Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap.RemovePermissionCollectionAsync(Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionRequest request) {
            return base.Channel.RemovePermissionCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionResponse> RemovePermissionCollectionAsync(string objectName, string objectType, System.Xml.Linq.XElement memberIdsXml) {
            Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionRequest inValue = new Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionRequest();
            inValue.Body = new Umebayashi.Enterprise.SharePoint.Services.Permissions.RemovePermissionCollectionRequestBody();
            inValue.Body.objectName = objectName;
            inValue.Body.objectType = objectType;
            inValue.Body.memberIdsXml = memberIdsXml;
            return ((Umebayashi.Enterprise.SharePoint.Services.Permissions.PermissionsSoap)(this)).RemovePermissionCollectionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.PermissionsSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.PermissionsSoap)) {
                return new System.ServiceModel.EndpointAddress("http://umebayashi.sharepoint.com/_vti_bin/Permissions.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return PermissionsSoapClient.GetBindingForEndpoint(EndpointConfiguration.PermissionsSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return PermissionsSoapClient.GetEndpointAddress(EndpointConfiguration.PermissionsSoap);
        }
        
        public enum EndpointConfiguration {
            
            PermissionsSoap,
        }
    }
}
